name: StevenPemberton.Net
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title
exclude: ['fsharp-posts', 'tools', 'packages', 'SJPemberton.Net.sln']
excerpt_separator: "<!-- more -->"